[package]
name = "hey-notes-api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.9", features = ["multipart"] }
dotenvy = "0.15.7"
reqwest = { version = "0.13.5", default-features = false, features = ["rustls", "multipart", "json", "http2"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.2", features = ["macros", "rt-multi-thread", "signal", "time", "sync"] }
tower-http = { version = "0.7.1", features = ["limit", "trace"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
